### ISSUE TITLE
Improve categorization of images prefixed with "User"

### ISSUE THREAD

**Issue by Tarkoviski** [jbzdarkid/3D-Models-automaton#3]
Users are testing the script in their user space (which is good!), but they often need to manually edit the generated page, usually to remove the "[3D model images](https://wiki.teamfortress.com/wiki/Category:3D_model_images)" category and replace it with the proper "[User images](https://wiki.teamfortress.com/wiki/Category:User_images)" category. I think a simple tweak to improve this behavior would be a welcome minor qol change.

I haven't delved too deeply into the code, but I believe something like this in automate.py#L122-L136 could work:
```diff
 title = title.replace(' ', '_')
 hash_ = hashlib.md5(title.encode('utf-8')).hexdigest()
 url = 'https://wiki.teamfortress.com/w/images/%s/%s/%s' % (hash_[:1], hash_[:2], quote(title))
+category = '3D model images' if not title.startswith('User_') else 'User images'
 description = '''{{{{#switch: {{{{1|}}}}
 | url = <nowiki>%s?%s</nowiki>
 | map = \n%s
 | height = %d
 | startframe = 16
-}}}}<noinclude>{{3D viewer}}[[Category:3D model images]]
+}}}}<noinclude>{{3D viewer}}[[Category:%s]]
 {{Externally linked}}''' % (
     url,
     datetime.utcnow().timestamp(),
-    ip.target_dimension
+    ip.target_dimension,
+    category
 )

**Comment by jbzdarkid** [comment]
Looks reasonable, make a pull request?
